### ISSUE TITLE
Windows firewall extras module is broken

### ISSUE THREAD

**Issue by giulianob** [ansible/ansible-modules-extras#1050]
The module is just erroring out on the most basic usage. I would try to submit a PR but I'm not even sure how to debug it.

```
   - name: Configure firewall
     win_firewall_rule: name=test protocol=TCP action=allow direction=in localport=999 state=present
```

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/ansible/lib/ansible/executor/process/worker.py", line 117, in run
    executor_result = TaskExecutor(host, task, job_vars, play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/home/vagrant/ansible/lib/ansible/executor/task_executor.py", line 118, in run
    res = self._execute()
  File "/home/vagrant/ansible/lib/ansible/executor/task_executor.py", line 343, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/vagrant/ansible/lib/ansible/plugins/action/normal.py", line 26, in run
    results = self._execute_module(tmp=tmp, task_vars=task_vars)
  File "/home/vagrant/ansible/lib/ansible/plugins/action/__init__.py", line 409, in _execute_module
    cmd = self._connection._shell.build_module_command(environment_string, shebang, cmd, arg_path=args_file_path, rm_tmp=rm_tmp)
TypeError: build_module_command() got an unexpected keyword argument 'arg_path'

fatal: [xxx]: FAILED! => {"failed": true, "stdout": ""}
```

Also, the module documentation says to use "win_fw" but the actual module is named "win_firewall_rule"

@TimothyVandenbrande  any clue? I'd be happy to help if needed

**Comment by giulianob** [comment]
I think it might be a more crosscutting issue w/ windows modules in my dev build
