### ISSUE TITLE
npm module traceback

### ISSUE THREAD

**Issue by Morriz** [ansible/ansible-modules-extras#111]
this playbook:
- hosts: all
  tasks:
  - name: install global npm packages
    npm: name={{ item }} global=yes state=latest
    with_items:
    - gulp

gives this error:

TASK: [install global npm packages] ******************************************\* 
failed: [localhost] => (item=gulp) => {"failed": true, "item": "gulp", "parsed": false}
Traceback (most recent call last):
  File "/Users/Morriz/.ansible/tmp/ansible-tmp-1416254319.77-187721358027197/npm", line 1828, in <module>
    main()
  File "/Users/Morriz/.ansible/tmp/ansible-tmp-1416254319.77-187721358027197/npm", line 248, in main
    installed, missing = npm.list()
  File "/Users/Morriz/.ansible/tmp/ansible-tmp-1416254319.77-187721358027197/npm", line 167, in list
    data = json.loads(self._exec(cmd, True, False))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mpdehaan** [comment]
Can you please share more information about what version of Ansible, npm, and OS you are using?

Thanks!

**Comment by Morriz** [comment]
Nevermind, I had node install errors that got unnoticed by ansible, and as such I didn't have npm ;|
