### ISSUE TITLE
vsphere_copy issues

### ISSUE THREAD

**Issue by wyaeld** [ansible/ansible-modules-extras#1397]
##### Issue Type:

Module Bug Report / Unclear examples
##### Ansible Version:

```
15:39 $ ansible --version
ansible 2.0.0 (stable-2.0 bcd66059ae) last updated 2015/12/18 15:33:17 (GMT +1300)
  lib/ansible/modules/core: (detached HEAD 717604572f) last updated 2015/12/18 15:33:22 (GMT +1300)
  lib/ansible/modules/extras: (detached HEAD 46734ba8f6) last updated 2015/12/18 15:33:41 (GMT +1300)
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

none
##### Environment:

Ubuntu 14.04 talking to Vcenter/Esxi 5.5
##### Summary:

Trying to upload files using vsphere_copy.  @matburt I see you made some fixes here recently, which I made sure I had, so I'm also assuming you have working examples.  This could just be operator error, I'm running into low-level errors that aren't giving me much to go on.
##### Steps To Reproduce:

playbook as below

```

---
- name: Upload VSphere machine
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    vcenter_hostname: xxx
    username: xxx
    password: xxx
    datacenter: Alabs-G5
    datastore: datastore1
    src: "/home/brad/Public/bradtest"
    path: rhel-6.7-brad

  tasks: 
  - name: upload packer machine to vcenter
    vsphere_copy: >
      host={{vcenter_hostname}}
      login={{username}}
      password={{password}}
      src={{src}}
      datacenter={{datacenter}}
      datastore={{datastore}}
      path={{path}}
      validate_certs=no


```
##### Expected Results:

Expected to upload file/files and have them show up in datastore.  Its not clear from examples though how to do directories vs files, or whether the datastore cluster details can just be skipped.
##### Actual Results:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/brad/.ansible/tmp/ansible-tmp-1450406395.85-8912898199797/vsphere_copy", line 2896, in <module>
    main()
  File "/home/brad/.ansible/tmp/ansible-tmp-1450406395.85-8912898199797/vsphere_copy", line 153, in main
    if isinstance(e[0], int):
IndexError: tuple index out of range

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"datacenter": "Alabs-G5", "datastore": "datastore1", "host": "xxx", "login": "xxx", "password": "xxx", "path": "rhel-6.7-brad", "src": "/home/brad/Public/bradtest", "validate_certs": "no"}, "module_name": "vsphere_copy"}, "parsed": false}
```

**Comment by matburt** [comment]
I think I mentioned this on my PR but the exception handling for `vsphere_copy` needs to be updated after the switch to `open_url` and I just haven't had a chance to circle back to that yet.

You can fix up the module locally here:
https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/vmware/vsphere_copy.py#L151

basically just shortcut or remove that whole try block to see what exception is being thrown and for your sake I hope it's not `urlopen error [Errno 32] Broken pipe` because after doing that that's the error I get 9 times out of 10 (for bad passwords etc.).

I think `open_url` might need some love in order to give an accurate error back to the module.  If I can't get to it soonish @chrrrles has been giving the vmware modules a refresh and might be able to come up with a more elegant solution.

**Comment by wyaeld** [comment]
removed the whole try, error is `405 Method Not Allowed`

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/brad/.ansible/tmp/ansible-tmp-1450408497.97-174563211158003/vsphere_copy", line 2896, in <module>
    main()
  File "/home/brad/.ansible/tmp/ansible-tmp-1450408497.97-174563211158003/vsphere_copy", line 143, in main
    force_basic_auth=True)
  File "/home/brad/.ansible/tmp/ansible-tmp-1450408497.97-174563211158003/vsphere_copy", line 2823, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 405: Method Not Allowed

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"datacenter": "Alabs-G5", "datastore": "datastore1", "host": "xxx", "login": "xxx", "password": "xxx", "path": "rhel-6.7-brad", "src": "/home/brad/Public/bradtest", "validate_certs": "no"}, "module_name": "vsphere_copy"}, "parsed": false}
```

**Comment by wyaeld** [comment]
Ok, more progress now.  Got 201 created.  If `path` is the destination folder, rather than `folder/filename` then doesn't work.

I'll close this shortly but @matburt do you know if there is a way to upload folders?  I've just now adapted my playbook to be

```
---
- name: Upload VSphere machine
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    vcenter_hostname: xxx
    username: xxx
    password: xxx
    datacenter: Alabs-G5
    datastore: datastore1
    src_folder: /home/brad/Public/packer-rhel-6.7-x86_64-vmware
    dest_folder: rhel-6.7-brad

  tasks: 
  - name: upload packer machine to vcenter
    vsphere_copy: >
      host={{vcenter_hostname}}
      login={{username}}
      password={{password}}
      src={{src_folder}}/{{item}}
      datacenter={{datacenter}}
      datastore={{datastore}}
      path={{dest_folder}}/{{item}}
      validate_certs=no
    with_items:
      - disk.vmdk
      - disk-s001.vmdk
      - disk-s002.vmdk
      - disk-s003.vmdk
      - rhel-6.7-x86_64.nvram
      - rhel-6.7-x86_64.vmsd
      - rhel-6.7-x86_64.vmx
      - rhel-6.7-x86_64.vmxf
```

**Comment by matburt** [comment]
As far as I know this isn't supported by the http api of the vsphere server itself.

**Comment by wyaeld** [comment]
OK thanks.  I'll close this now, although I'll probably contribute a variation of the above as a multi-file example just for the module to help others.
