### ISSUE TITLE
ec2_vpc_route_table issue with adding new rule

### ISSUE THREAD

**Issue by ulmen** [ansible/ansible-modules-extras#1556]
Hey guys, trying to use ec2_vpc_route_table module and have some issues with it.

One of them:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/ulmen/.ansible/tmp/ansible-tmp-1453816937.56-101298908931730/ec2_vpc_route_table", line 2760, in <module>
    main()
  File "/Users/ulmen/.ansible/tmp/ansible-tmp-1453816937.56-101298908931730/ec2_vpc_route_table", line 589, in main
    result = ensure_route_table_present(connection, module)
  File "/Users/ulmen/.ansible/tmp/ansible-tmp-1453816937.56-101298908931730/ec2_vpc_route_table", line 512, in ensure_route_table_present
    result = ensure_routes(connection, route_table, routes, propagating_vgw_ids, check_mode)
  File "/Users/ulmen/.ansible/tmp/ansible-tmp-1453816937.56-101298908931730/ec2_vpc_route_table", line 329, in ensure_routes
    **route_spec)
TypeError: create_route() got an unexpected keyword argument 'vpc_peering_connection'

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_vpc_route_table"}, "parsed": false}
```

How to reproduce:
just add new route rule pointed to vpc_peering_connection to ansible playbook which describes existing route table

Ansible version: 2.0.0.2

**Comment by ulmen** [comment]
My fault, proper key name is `vpc_peering_connection_id`
