### ISSUE TITLE
Composer - JSON parsing error when using a 30+ days old build of composer

### ISSUE THREAD

**Issue by rdevaissiere** [ansible/ansible-modules-extras#1955]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

composer
##### ANSIBLE VERSION

2.0.1.0
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

**NOTE:** likely more of a `composer` bug but I'm referencing it here anyway in hope to help others.

A JSON parsing error is raised when using a 30+ days old build of composer.
##### STEPS TO REPRODUCE
- Make sure you're running a 30+ days old build of composer
- Have a composer task running any command such as `composer: command=about working_dir=<path>`
##### EXPECTED RESULTS

No errors
##### ACTUAL RESULTS

The task fails with the following error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: No JSON object could be decoded
```

With the full stack trace:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 2186, in <module>
  File "<stdin>", line 179, in main
  File "<stdin>", line 147, in get_available_options
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The error appears to be caused by this commit/line where the module attempts to extract a list of available options for a given command:

https://github.com/ansible/ansible-modules-extras/pull/965/commits/384eaba7662fbf5c794d7ace26786f41fa1e4de1#diff-6c23e90010d0730f62429dcf4f4d68c2R123

Problem is, when running an old version of composer, it issues the following warning and includes it in the "JSON output":

```
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
```

There doesn't seem to be a `composer` option to simply silence this warning. I've opened a bug with composer as they're pretending to output JSON when they're not.

https://github.com/composer/composer/issues/5147

**Comment by rdevaissiere** [comment]
Fixed a year ago by composer (https://github.com/composer/composer/commit/cb336a5416595efa321c024735e6452c9c7df106). Moral of the story? Update composer ;-)
