### ISSUE TITLE
lxc container module is broken in 1.9.6

### ISSUE THREAD

**Issue by cloudnull** [ansible/ansible-modules-extras#2042]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME
- lxc_container 
##### ANSIBLE VERSION

```
ansible 1.9.6
```
##### CONFIGURATION

``` ini
[defaults]
# Additional plugins
lookup_plugins = /etc/ansible/plugins/lookup
filter_plugins = /etc/ansible/plugins/filter
action_plugins = /etc/ansible/plugins/action
library = /etc/ansible/plugins/library

# Fact caching
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /etc/openstack_deploy/ansible_facts
fact_caching_timeout = 86400

inventory = inventory
host_key_checking = False

# Set color options
nocolor = 0

# SSH timeout
timeout = 120

[ssh_connection]
pipelining = True
```
##### OS / ENVIRONMENT

Ubuntu 14.04.04
##### SUMMARY

The lxc_container module is broken in Ansible "1.9.6". This brokeness comes from the commit https://github.com/ansible/ansible-modules-extras/commit/30e0c507e7b86e66662ad59367c9a97c0c19cd3b which introduced changes for 2.x which do not exist in ansible "1.9". Specifically the `required_if` function does not exist in `lib/ansible/module_utils/basic.py`. Additionally even with that method removed from the module the archive check needs to be adjusted to check to see if the _archive_ option is in the **BOOLEANS_TRUE** constant.
##### STEPS TO REPRODUCE

``` shell
ansible -m lxc_container -a 'name=test-container' infra1
infra1 | FAILED >> {
    "failed": true,
    "msg": "OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/ansible-ssh-172.29.236.100-22-root\" does not exist\r\ndebug1: Connecting to 172.29.236.100 [172.29.236.100] port 22.\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug1: permanently_set_uid: 0/0\r\ndebug1: identity file /root/.ssh/id_rsa type 1\r\ndebug1: identity file /root/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /root/.ssh/id_dsa type -1\r\ndebug1: identity file /root/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /root/.ssh/id_ecdsa type -1\r\ndebug1: identity file /root/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /root/.ssh/id_ed25519 type -1\r\ndebug1: identity file /root/.ssh/id_ed25519-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6\r\ndebug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6 pat OpenSSH_6.6.1* compat 0x04000000\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com\r\ndebug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com\r\ndebug1: sending SSH2_MSG_KEX_ECDH_INIT\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug1: Server host key: ECDSA ec:7d:3b:4a:c9:2d:cd:99:41:8a:90:6a:4c:42:53:02\r\ndebug1: Host '172.29.236.100' is known and matches the ECDSA host key.\r\ndebug1: Found key in /root/.ssh/known_hosts:9\r\ndebug1: ssh_ecdsa_verify: signature correct\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug1: SSH2_MSG_SERVICE_REQUEST sent\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\n------------------------------------------------------------------------------\n* WARNING                                                                    *\n* You are accessing a secured system and your actions will be logged along   *\n* with identifying information. Disconnect immediately if you are not an     *\n* authorized user of this system.                                            *\n------------------------------------------------------------------------------\ndebug1: Authentications that can continue: publickey,password\r\ndebug1: Next authentication method: publickey\r\ndebug1: Offering RSA public key: /root/.ssh/id_rsa\r\ndebug1: Server accepts key: pkalg ssh-rsa blen 279\r\ndebug1: key_parse_private2: missing begin marker\r\ndebug1: read PEM private key done: type RSA\r\ndebug1: Enabling compression at level 6.\r\ndebug1: Authentication succeeded (publickey).\r\nAuthenticated to 172.29.236.100 ([172.29.236.100]:22).\r\ndebug1: setting up multiplex master socket\r\ndebug1: channel 0: new [/root/.ansible/cp/ansible-ssh-172.29.236.100-22-root]\r\ndebug1: control_persist_detach: backgrounding master process\r\ndebug1: forking to background\r\ndebug1: Entering interactive session.\r\ndebug1: multiplexing control connection\r\ndebug1: channel 1: new [mux-control]\r\ndebug1: channel 2: new [client-session]\r\ndebug1: Sending environment.\r\ndebug1: Sending env LANG = en_US.UTF-8\r\ndebug1: Sending command: /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'\r\ndebug1: mux_client_request_session: master session id: 2\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 3117, in <module>\n  File \"<stdin>\", line 1462, in main\nTypeError: __init__() got an unexpected keyword argument 'required_if'\ndebug1: client_input_channel_req: channel 2 rtype exit-status reply 0\r\ndebug1: channel 2: free: client-session, nchannels 3\r\ndebug1: channel 1: free: mux-control, nchannels 2\r\n",
    "parsed": false
}
```

##### EXPECTED RESULTS

The container should build.
##### ACTUAL RESULTS

The module stops. See command output for action stdout/stderr
##### FIX FOR ANSIBLE 1.9.6

http://paste.openstack.org/show/494312/

**Comment by cloudnull** [comment]
It would seem that the LXC container module in 1.9.6 is broken due to an incompatible change being backported. Is it possible to get a change into 1.9.6 to resolve this issue? At current the OpenStack-Ansible project is unable to use 1.9.6 as is. This is an example of the error: http://logs.openstack.org/09/306609/2/check/gate-openstack-ansible-dsvm-commit/1fd66a3/console.html#_2016-04-15_21_03_52_758

``` traceback
2016-04-15 21:03:52.758 | failed: [aio1_nova_scheduler_container-8be705e1 -> aio1] => {"failed": true, "parsed": false}
2016-04-15 21:03:52.758 | OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
2016-04-15 21:03:52.758 | debug1: Reading configuration data /etc/ssh/ssh_config
2016-04-15 21:03:52.758 | debug1: /etc/ssh/ssh_config line 19: Applying options for *
2016-04-15 21:03:52.758 | debug1: auto-mux: Trying existing master
2016-04-15 21:03:52.758 | debug1: mux_client_request_session: master session id: 2
2016-04-15 21:03:52.758 | Traceback (most recent call last):
2016-04-15 21:03:52.759 |   File "<stdin>", line 3117, in <module>
2016-04-15 21:03:52.759 |   File "<stdin>", line 1462, in main
2016-04-15 21:03:52.759 | TypeError: __init__() got an unexpected keyword argument 'required_if'
```

-cc @evgeni @gregdek @robynbergeron

**Comment by cloudnull** [comment]
Just to confirm everything in devel works fine as is. This issue seems to only effect 1.9.6.

``` shell
Command: ansible '-m' 'lxc_container' '-a' 'name=test-container' 'infra1'
infra1 | SUCCESS => {
    "changed": true, 
    "lxc_container": {
        "init_pid": 25918, 
        "interfaces": [
            "eth0", 
            "lo"
        ], 
        "ips": [], 
        "name": "test-container", 
        "state": "running"
    }
}
ansible '--version'
ansible 2.1.0
  config file = /opt/openstack-ansible/playbooks/ansible.cfg
  configured module search path = ['/etc/ansible/plugins/library']
```

**Comment by evgeni** [comment]
yepp, seems this was overseen when backporting my patches to 1.9.x
your patch looks fine to me, even if I'd have used `and` instead of `all()`.
:+1:

**Comment by cloudnull** [comment]
I'm not sure what the process is to get the fix into 1.9.6 -- @resmo @evgeni?
@evgeni with regard to `and` vs `all` I'm happy either way :)

**Comment by gregdek** [comment]
Will escalate to the core team to see if they can cherry pick.

**Comment by cloudnull** [comment]
Thanks @gregdek -- Much appreciated!

**Comment by abadger** [comment]
@cloudnull looking into this right now.

**Comment by abadger** [comment]
@cloudnull -- Yeah, required_if definitely needs to be removed there for 1.9... Looks like the other section of code repeats what required_if does so we don't need both.  I'm not sure why you think we need to compare the parameter to BOOLEANS_TRUE, though.  Could you explain that portion?

**Comment by abadger** [comment]
I'm abadger1999 on freenode if you want to find me in #ansible or #ansible-devel

**Comment by abadger** [comment]
@cloudnull -- nevermind I see why it's needed but there's a better way to do that.  The arg_spec should be setting type='bool' and setting default=False instead of using choices=BOOLEANS.

**Comment by robynbergeron** [comment]
@cloudnull -- know offhand if the fix from @abadger made things happier?

**Comment by cloudnull** [comment]
@robynbergeron At last check the fixes in stable1.9 made things a lot happier. I will reverify and post back shortly.

**Comment by cloudnull** [comment]
@robynbergeron Stable-1.9 installed from github looks good.

``` shell
Command: pip 'install' 'git+https://github.com/ansible/ansible@stable-1.9'
Command: ansible '-m' 'lxc_container' '-a' 'name=test-container2' 'aio1'
aio1 | success >> {
    "changed": true, 
    "lxc_container": {
        "init_pid": 14922, 
        "interfaces": [
            "eth0", 
            "lo"
        ], 
        "ips": [], 
        "state": "running"
    }
}

Command: ansible '-m' 'lxc_container' '-a' 'name=test-container2' 'aio1'
aio1 | success >> {
    "changed": false, 
    "lxc_container": {
        "init_pid": 14922, 
        "interfaces": [
            "eth0", 
            "lo"
        ], 
        "ips": [
            "10.255.255.160"
        ], 
        "state": "running"
    }
}

Command: ansible '--version'
ansible 1.9.6
  configured module search path = /etc/ansible/roles/plugins/library
```

**Comment by abadger** [comment]
Cool.  Thanks for reporting and testing!
