### ISSUE TITLE
Amazon - ec2_vpc_route_table - TypeError when propagating existing routes with NGW

### ISSUE THREAD

**Issue by mdaize** [ansible/ansible-modules-extras#2377]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_vpc_route_table
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

TypeError present when re-running ec2_vpc_route_table after VPC is already created. The erroneous routes are those where the default route 0.0.0.0/0 are pointed at the NAT Gateway. The TypeError seems to occur when it attempts to loop through the routes when it attempts to check the list propagating_vgw_ids (ec2_vpc_route_table.py: Line 320-322).
##### STEPS TO REPRODUCE

- Create a VPC
- Create route tables using 'ec2_vpc_route_table'
- Create NAT Gateway
- Update the route tables using the NAT Gateway IDs
- Re-run the playbook - - the route table creation fails with the TypeError

```
aws_vpc_route_table_info:
  - resource_tags: { "Name": "Private-NAT-{{ aws_az_2|upper }}" }
    subnets:
      - "172.25.10.0/24"
      - "172.25.18.0/24"
      - "172.25.26.0/24"
      - "172.25.34.0/24"
      - "172.25.42.0/24"
      - "172.25.50.0/24"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "igw"
```

This is followed with the AWS CLI call to replace_route of the prescribed route table to replace the IGW route with the proper NAT Gateway ID:

```
shell: "export AWS_ACCESS_KEY_ID={{ aws_access_key }}; export AWS_SECRET_ACCESS_KEY={{ aws_secret_key }}; aws --region {{aws_region }} ec2 replace-route --route-table-id {{ aws_vpc_route_table_id }} --destination-cidr-block {{ outer_loop.dest }} --gateway-id {{ aws_vpc_nat_gateway_id }}"
```

##### EXPECTED RESULTS

Successful operation.
##### ACTUAL RESULTS

It works the first time it's run.

The second time run, the result is:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py", line 613, in <module>
    main()
  File "/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py", line 601, in main
    result = ensure_route_table_present(connection, module)
  File "/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py", line 524, in ensure_route_table_present
    result = ensure_routes(connection, route_table, routes, propagating_vgw_ids, module.check_mode)
  File "/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py", line 324, in ensure_routes
    and r.gateway_id not in propagating_vgw_ids]
TypeError: argument of type 'NoneType' is not iterable

failed: [localhost] (item={u'routes': [{u'dest': u'0.0.0.0/0', u'gateway_id': u'igw'}], u'resource_tags': {u'Name': u'Private-NAT-B'}, u'subnets': [u'172.25.10.0/24', u'172.25.18.0/24', u'172.25.26.0/24', u'172.25.34.0/24', u'172.25.42.0/24', u'172.25.50.0/24']}) => {"failed": true, "invocation": {"module_name": "ec2_vpc_route_table"}, "item": {"resource_tags": {"Name": "Private-NAT-B"}, "routes": [{"dest": "0.0.0.0/0", "gateway_id": "igw"}], "subnets": ["172.25.10.0/24", "172.25.18.0/24", "172.25.26.0/24", "172.25.34.0/24", "172.25.42.0/24", "172.25.50.0/24"]}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py\", line 613, in <module>\n    main()\n  File \"/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py\", line 601, in main\n    result = ensure_route_table_present(connection, module)\n  File \"/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py\", line 524, in ensure_route_table_present\n    result = ensure_routes(connection, route_table, routes, propagating_vgw_ids, module.check_mode)\n  File \"/tmp/ansible_7tCqt2/ansible_module_ec2_vpc_route_table.py\", line 324, in ensure_routes\n    and r.gateway_id not in propagating_vgw_ids]\nTypeError: argument of type 'NoneType' is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by bnaydenov** [comment]
Exactly the same behaviour is reproduced also with ansible 2.1.0.0

**Comment by captainkerk** [comment]
Opened a PR with the fix:
https://github.com/ansible/ansible-modules-extras/pull/2421

**Comment by kaikousa** [comment]
Had the same issue, workaround was to set the attribute into an empty array.

``` yaml
propagating_vgw_ids: []
```
