### ISSUE TITLE
win_chocolatey ERROR: Thread failed to start installing googlechrome

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-modules-extras#2580]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_chocolatey 
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (devel 134d70e7b9) last updated 2016/07/16 22:02:07 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/16 22:02:07 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/16 22:02:07 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ansible host OS X 10.11.5
Managed host Windows 7 64-bit
##### SUMMARY

Try install Google Chrome via win_chocolatey and it fails (details below)
##### STEPS TO REPRODUCE

```
- name: install Google Chrome (choco)
  win_chocolatey:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - "googlechrome"
```

##### EXPECTED RESULTS

Google Chrome to be installed. 

Installing Google Chrome via a powershell command line

```
> choco install googlechrome
```

Works as expected. So I think the bug is in Ansible win_chocolatey, not chocolatey itself.
##### ACTUAL RESULTS

```
TASK [win-win7-workstation : install Google Chrome (choco)] ********************
failed: [win71616D] (item=googlechrome) => {"changed": false, "choco_error_cmd": "choco.exe install -dv -y googlechrome", "choco_error_log": "Chocolatey is running on Windows v 6.1.7601.65536 Attempting to delete file \"C:/ProgramData/chocolatey/choco.exe.old\". Attempting to delete file \"C:\\ProgramData\\chocolatey\\choco.exe.old\". Command line: \"C:\\ProgramData\\chocolatey\\choco.exe\" install -dv -y googlechrome Received arguments: install -dv -y googlechrome RemovePendingPackagesTask is now ready and waiting for PreRunMessage. Sending message 'PreRunMessage' out if there are subscribers... [Pending] Removing all pending packages that should not be considered installed... The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type  NOTE: Hiding sensitive configuration data! Please double and triple   check to be sure no sensitive data is shown, especially if copying   output to a gist for review. Configuration: CommandName='install'| CacheLocation='C:\\Users\\Administrator\\AppData\\Local\\Temp\\chocolatey'| ContainsLegacyPackageInstalls='True'| CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'| Sources='https://chocolatey.org/api/v2/'|SourceType='normal'| Debug='True'|Verbose='True'|Force='False'|Noop='False'| HelpRequested='False'|RegularOutput='True'|QuietOutput='False'| PromptForConfirmation='False'|AcceptLicense='True'| AllowUnofficialBuild='False'|Input='googlechrome'|AllVersions='False'| SkipPackageInstallProvider='False'|PackageNames='googlechrome'| Prerelease='False'|ForceX86='False'|OverrideArguments='False'| NotSilent='False'|IgnoreDependencies='False'| AllowMultipleVersions='False'|AllowDowngrade='False'| ForceDependencies='False'|Information.PlatformType='Windows'| Information.PlatformVersion='6.1.7601.65536'| Information.PlatformName='Windows 7'| Information.ChocolateyVersion='0.9.10.3'| Information.ChocolateyProductVersion='0.9.10.3'| Information.FullName='choco, Version=0.9.10.3, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|  Information.Is64Bit='True'|Information.IsInteractive='False'| Information.IsUserAdministrator='True'| Information.IsProcessElevated='True'| Information.IsLicensedVersion='False'|Features.AutoUninstaller='True'| Features.CheckSumFiles='True'|Features.FailOnAutoUninstaller='False'| Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'| Features.LogEnvironmentValues='False'|Features.VirusCheck='False'| Features.FailOnInvalidOrMissingLicense='False'| Features.IgnoreInvalidOptionsSwitches='True'| Features.UsePackageExitCodes='True'| Features.UseFipsCompliantChecksums='False'| ListCommand.LocalOnly='False'| ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'| ListCommand.Exact='False'|ListCommand.ByIdOnly='False'| ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'| ListCommand.ApprovedOnly='False'| ListCommand.DownloadCacheAvailable='False'| ListCommand.NotBroken='False'|UpgradeCommand.FailOnUnfound='False'| UpgradeCommand.FailOnNotInstalled='False'| UpgradeCommand.NotifyOnlyAvailableUpgrades='False'| NewCommand.AutomaticPackage='False'| NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'| SourceCommand.Priority='0'|FeatureCommand.Command='unknown'| ConfigCommand.Command='unknown'|PinCommand.Command='unknown'| _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _ Installing the following packages: googlechrome By installing you accept licenses for the packages. [NuGet] Installing 'GoogleChrome 51.0.2704.106'. [NuGet] Added file 'chocolateyInstall.ps1' to folder 'GoogleChrome\\tools'. [NuGet] Added file 'chocolateyUninstall.ps1' to folder 'GoogleChrome\\tools'. [NuGet] Added file 'GoogleChrome.nuspec' to folder 'GoogleChrome'. [NuGet] Added file 'GoogleChrome.nupkg' to folder 'GoogleChrome'. [NuGet] Successfully installed 'GoogleChrome 51.0.2704.106'.  GoogleChrome v51.0.2704.106 [Approved] Setting installer args and package parameters for GoogleChrome Contents of 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\tools\\chocolateyInstall.ps1': $packageName = 'GoogleChrome' $fileType = 'msi' $silentArgs = '/quiet' $url = 'https://dl.google.com/tag/s/appguid={8A69D345-D564-463C-AFF1-A69D9E530F96}&iid={00000000-0000-0000-0000-000000000000}&lang=en&browser=3&usagestats=0&appname=Google Chrome&needsadmin=prefers/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi' $url64 = 'https://dl.google.com/tag/s/appguid={00000000-0000-0000-0000-000000000000}&iid={00000000-0000-0000-0000-000000000000}&lang=en&browser=4&usagestats=0&appname=Google Chrome&needsadmin=true/dl/chrome/install/googlechromestandaloneenterprise64.msi' $version = '51.0.2704.106'  # This function checks if Chrome 32-bit is installed # on a 64-bit system function Check-Chrome32bitInstalled {    $registryPath = 'HKLM:\\SOFTWARE\\WOW6432Node\\Google\\Update\\ClientState\\'    if (Test-Path $registryPath) {     Get-ChildItem $registryPath | ForEach-Object {       if ((Get-ItemProperty $_.pspath).ap -eq '-multi-chrome') {         return $true       }     }   } }  function Find-CID {   param([String]$croot, [string]$cdname, [string]$ver)    if (Test-Path $croot) {      Get-ChildItem -Force -Path $croot | foreach {       $CurrentKey = (Get-ItemProperty -Path $_.PsPath)       if ($CurrentKey -match $cdname -and $CurrentKey -match $ver) {         return $CurrentKey.PsChildName       }     }   }    return $null }  $uroot = 'HKLM:\\SOFTWARE\\Google\\Update\\Clients' $uroot64 = 'HKLM:\\SOFTWARE\\Wow6432Node\\Google\\Update\\Clients'   $msid = Find-CID $uroot \"Google Chrome binaries\" \"$version\" if ($msid -eq $null) { # try 64bit registry   $msid = Find-CID $uroot64 \"Google Chrome binaries\" \"$version\" } if ($msid -ne $null) {    Write-Output \"Google Chrome $version is already installed.\" } else {    # If Chrome 32-bit is already installed on a 64-bit system,   # keep installing the 32-bit version, otherwise install the   # 64-bit version on 64-bit systems   if (Check-Chrome32bitInstalled) {     Install-ChocolateyPackage $packageName $fileType $silentArgs $url   } else {     Install-ChocolateyPackage $packageName $fileType $silentArgs $url $url64   }  }  Calling built-in PowerShell host with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyInstaller.psm1'; & 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyScriptRunner.ps1' -packageScript 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\tools\\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] Redirecting System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35, requested by '' Attempting to load assembly System.Management.Automation.resources failed:  Could not load file or assembly 'System.Management.Automation.resources, Version=5.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. Attempting to load assembly System.Management.Automation.resources failed:  Could not load file or assembly 'System.Management.Automation.resources, Version=4.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. Attempting to load assembly System.Management.Automation.resources failed:  Could not load file or assembly 'System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. Attempting to load assembly System.Management.Automation.resources failed:  Could not load file or assembly 'System.Management.Automation.resources, Version=1.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. ERROR: Thread failed to start.     at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)    at System.Threading.Thread.Start(StackCrawlMark& stackMark)    at System.Threading.Thread.Start()    at System.Management.Automation.Runspaces.LocalPipeline.StartPipelineExecution()    at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)    at chocolatey.infrastructure.app.services.PowershellService.run_host(ChocolateyConfiguration config, String chocoPowerShellScript, Action`1 additionalActionsBeforeScript) Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyInstaller.psm1'; & 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyScriptRunner.ps1' -packageScript 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\tools\\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'. Calling command ['\"C:\\Windows\\System32\\shutdown.exe\" /a'] Command ['\"C:\\Windows\\System32\\shutdown.exe\" /a'] exited with '1116' Capturing package files in 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome'  Found 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\.chocolateyPending'   with checksum '01F442AA92FD8ADB60C88C0617C6A94A'  Found 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\GoogleChrome.nupkg'   with checksum 'FF8B6D8C9683947412B2FBD5E7875033'  Found 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\GoogleChrome.nuspec'   with checksum 'D02AC040D8E7A3FB7D8F31AC34E36B4B'  Found 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\tools\\chocolateyInstall.ps1'   with checksum '295900932C63D775408F989E2426B3B4'  Found 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\tools\\chocolateyUninstall.ps1'   with checksum '250B2C17E9F17E3761F4EAD106F0FCD6' Attempting to create directory \"C:\\ProgramData\\chocolatey\\.chocolatey\\GoogleChrome.51.0.2704.106\". Attempting to copy \"C:\\ProgramData\\chocolatey\\.chocolatey\\GoogleChrome.51.0.2704.106\\.files.update\"  to \"C:\\ProgramData\\chocolatey\\.chocolatey\\GoogleChrome.51.0.2704.106\\.files\". Attempting to delete file \"C:\\ProgramData\\chocolatey\\.chocolatey\\GoogleChrome.51.0.2704.106\\.files.update\". Attempting to delete file \"C:\\ProgramData\\chocolatey\\.chocolatey\\GoogleChrome.51.0.2704.106\\.sxs\". Attempting to delete file \"C:\\ProgramData\\chocolatey\\.chocolatey\\GoogleChrome.51.0.2704.106\\.pin\". Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers... The install of googlechrome was NOT successful. Error while running 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\tools\\chocolateyInstall.ps1'.  See log for details. Attempting to create directory \"C:\\ProgramData\\chocolatey\\lib-bad\". Moving 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome'  to 'C:\\ProgramData\\chocolatey\\lib-bad\\GoogleChrome' Attempting to delete file \"C:\\Users\\Administrator\\AppData\\Local\\NuGet\\Cache\\GoogleChrome.51.0.2704.106.nupkg\".  Chocolatey installed 0/1 packages. 1 packages failed.  See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).  Failures  - googlechrome (exited -1) - Error while running 'C:\\ProgramData\\chocolatey\\lib\\GoogleChrome\\tools\\chocolateyInstall.ps1'.  See log for details. Sending message 'PostRunMessage' out if there are subscribers... Exiting with -1", "failed": true, "item": "googlechrome", "msg": "Error installing googlechrome"}
```

The chocolatey.log is pretty big, snippets of the [ERROR]s below.

```
2016-07-16 17:36:10,297 [ERROR] - ERROR: Thread failed to start.
    at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start()
   at System.Management.Automation.Runspaces.LocalPipeline.StartPipelineExecution()
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at chocolatey.infrastructure.app.services.PowershellService.run_host(ChocolateyConfiguration config, String chocoPowerShellScript, Action`1 additionalActionsBeforeScript)
2016-07-16 17:36:10,407 [ERROR] - The install of googlechrome was NOT successful.
2016-07-16 17:36:10,407 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.
 See log for details.
2016-07-16 17:36:12,435 [ERROR] - Failures
2016-07-16 17:36:12,435 [ERROR] -  - googlechrome (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.
 See log for details.
```

**Comment by nitzmahone** [comment]
Which Powershell version are you using this with? There are some bugs in WinRM/Powershell around job memory quotas on Win7/2008R2 that could cause this behavior...

**Comment by basictheprogram** [comment]
I should have added this version in the first bug report.

```
Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18444
BuildVersion                   6.2.9200.16398
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

**Comment by nitzmahone** [comment]
Yep, very likely [this issue](https://support.microsoft.com/en-us/kb/2842230)\- installing the hotfix or upgrading to PS4/PS5 should fix it. Please try one of those and update/close the issue accordingly. Thanks!

**Comment by basictheprogram** [comment]
Upgrading to Powershell 4.0 fixes this problem. I can also confirm Powershell 5.0 fixes the problem as well.

Thank you for the help.
Closing this issue.
