### ISSUE TITLE
asa_template: matched error in response: configure terminal

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-extras#3057]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

asa_template
##### ANSIBLE VERSION

```

```
##### SUMMARY

Module can't parse output of `configure terminal`
May be related to https://github.com/ansible/ansible-modules-extras/issues/3056

``` yaml

  File "/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/netcfg.py", line 54, in __call__
  File "/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/asa.py", line 88, in configure
  File "/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/shell.py", line 252, in execute
ansible.module_utils.network.NetworkError: matched error in response: configure terminal
         ^
ERROR: % Invalid input detected at '^' marker.
asav-1> 
```
##### STEPS TO REPRODUCE

``` yaml
- name: configure device with config
  asa_template:
    src: basic/config.j2
    provider: "{{ cli }}"
    force: yes
  register: result

```
##### ACTUAL RESULTS

``` yaml
TASK [test_asa_template : configure device with config] ************************
task path: /home/johnb/git/ansible-inc/test-asa/roles/test_asa_template/tests/cli/force.yaml:11
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/extras/network/asa/asa_template.py
<asa01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<asa01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475061354.52-253851014241495 `" && echo ansible-tmp-1475061354.52-253851014241495="` echo $HOME/.ansible/tmp/ansible-tmp-1475061354.52-253851014241495 `" ) && sleep 0'
<asa01> PUT /tmp/tmprUQIKE TO /home/johnb/.ansible/tmp/ansible-tmp-1475061354.52-253851014241495/asa_template.py
<asa01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1475061354.52-253851014241495/ /home/johnb/.ansible/tmp/ansible-tmp-1475061354.52-253851014241495/asa_template.py && sleep 0'
<asa01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1475061354.52-253851014241495/asa_template.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1475061354.52-253851014241495/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_gEEmAv/ansible_module_asa_template.py", line 172, in <module>
    main()
  File "/tmp/ansible_gEEmAv/ansible_module_asa_template.py", line 163, in main
    response = module.config(commands)
  File "/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/netcfg.py", line 54, in __call__
  File "/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/asa.py", line 88, in configure
  File "/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/shell.py", line 252, in execute
ansible.module_utils.network.NetworkError: matched error in response: configure terminal
         ^
ERROR: % Invalid input detected at '^' marker.
asav-1> 

fatal: [asa01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "force": true, 
            "provider": {
                "host": "asa01", 
                "password": "cisco", 
                "transport": "cli", 
                "username": "cisco"
            }, 
            "src": "object-group network OG-ANSIBLE-TEMPLATE\n description this is a test\n network-object host 192.168.99.12\n"
        }, 
        "module_name": "asa_template"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gEEmAv/ansible_module_asa_template.py\", line 172, in <module>\n    main()\n  File \"/tmp/ansible_gEEmAv/ansible_module_asa_template.py\", line 163, in main\n    response = module.config(commands)\n  File \"/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/netcfg.py\", line 54, in __call__\n  File \"/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/asa.py\", line 88, in configure\n  File \"/tmp/ansible_gEEmAv/ansible_modlib.zip/ansible/module_utils/shell.py\", line 252, in execute\nansible.module_utils.network.NetworkError: matched error in response: configure terminal\r\n         ^\r\nERROR: % Invalid input detected at '^' marker.\r\n\rasav-1> \n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

```

**Comment by gundalow** [comment]
Issue no longer applies as we have removed `asa_template` in 2.2
