### ISSUE TITLE
Ansible 'script' module does not work on windows guest (linux controller)

### ISSUE THREAD

**Issue by retrogradeorbit** [ansible/ansible-modules-extras#311]
Documentation here: http://docs.ansible.com/intro_windows.html
suggestst the script module should work. However, after getting windows control working (win_chocolatey works), using script results in:

```
fatal: [windows] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.9-py2.7.egg/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.9-py2.7.egg/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.9-py2.7.egg/ansible/runner/__init__.py", line 1026, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.9-py2.7.egg/ansible/runner/action_plugins/script.py", line 128, in run
    result = handler.run(conn, tmp, 'raw', module_args, inject)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.9-py2.7.egg/ansible/runner/action_plugins/raw.py", line 47, in run
    su=self.runner.su)
AttributeError: 'Runner' object has no attribute 'su'
```

$ ansible --version
ansible 1.9
  configured module search path = vp/share/ansible

Powershell version on windows guest is 4.0

**Comment by retrogradeorbit** [comment]
happens with raw module, too.
su set to no, and sudo set to no doesn't help.

**Comment by bcoca** [comment]
can you test current devel or 1.8.4? the bug you are seeing should be fixed in those versions

**Comment by retrogradeorbit** [comment]
Tested in devel. Yep, you're right. Bug is fixed.
