### ISSUE TITLE
"lxc_container" module needs to ensure multiple '=' signs are not split multiple times.

### ISSUE THREAD

**Issue by cloudnull** [ansible/ansible-modules-extras#325]
### Issue Type:

Bug Report
### Ansible Version:

ansible --version
ansible 1.9
### Environment:

Ubuntu 14.04.1 LTS
### Summary:

the lxc-container module is failing to parse options when the option string contains more than one '=' sign. This issue was originally reported by @jpic on the original module pull request as found here: "https://github.com/ansible/ansible-modules-extras/pull/123".
### Steps To Reproduce:

``` bash
cat > lxc-test.yml <<EOF
- name: setup container to run tests in
  sudo: yes
  lxc_container:
    name: test
    template: ubuntu
    state: started
    template_options: --release trusty
    container_config:
      - "lxc.aa_profile=unconfined"
      - "lxc.mount.entry=/mnt mnt none, defaults,bind,uid=0 0 0"
EOF

ansible-playbook lxc-test.yml -vvvv
```
### Expected Results:

The container is created successfully. The config for the container would then container the following values.

``` bash
grep -e 'aa_profile' -e 'mount.entry' /var/lib/lxc/test/config
lxc.aa_profile = unconfined
lxc.mount.entry = /mnt mnt none, defaults,bind,uid=0 0 0
```
### Actual Results:

``` bash
TASK: [lxc-container ] ********************************************************
<localhost> REMOTE_MODULE lxc-container template=ubuntu name=test state=started template_options='--release trusty'
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511 && echo $HOME/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511']
<localhost> PUT /tmp/tmpHgwgsI TO /root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container; rm -rf /root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container", line 3046, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container", line 1476, in main
    lxc_manage.run()
  File "/root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container", line 1373, in run
    action()
  File "/root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container", line 973, in _started
    self._started(count)
  File "/root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container", line 966, in _started
    self._config()
  File "/root/.ansible/tmp/ansible-tmp-1426737873.43-226732214108511/lxc-container", line 624, in _config
    for key, value in parsed_options:
ValueError: too many values to unpack
```
### How to Fix:

On line "https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/lxc/lxc_container.py#L619" the module needs to have the list comprehension changed to split on the first occurrence of the '=' sign.

This is the diff.

``` diff

diff --git a/playbooks/library/lxc-container b/playbooks/library/lxc-container
index 86b3d75..8f31a05 100755
--- a/playbooks/library/lxc-container
+++ b/playbooks/library/lxc-container
@@ -618,7 +618,7 @@ class LxcContainerManagement(object):
         # TODO(cloudnull) adjust import when issue has been resolved.
         import ast
         options_dict = ast.literal_eval(_container_config)
-        parsed_options = [i.split('=') for i in options_dict]
+        parsed_options = [i.split('=', 1) for i in options_dict]

         config_change = False
         for key, value in parsed_options:

```

**Comment by bcoca** [comment]
fixed by #326
