### ISSUE TITLE
gluster_volume reports "'module' is not defined"

### ISSUE THREAD

**Issue by rnowling** [ansible/ansible-modules-extras#397]
When using gluster_volume from trunk, I get the following:

```
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1429029637.19-120424794343984/gluster_volume", line 2036, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1429029637.19-120424794343984/gluster_volume", line 345, in main
    peers = get_peers()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1429029637.19-120424794343984/gluster_volume", line 166, in get_peers
    out = run_gluster([ 'peer', 'status'])
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1429029637.19-120424794343984/gluster_volume", line 144, in run_gluster
    module.fail_json(msg='error running gluster (%s) command: %s' % (' '.join(args), str(e)))
NameError: global name 'module' is not defined
```

`module` is defined in `main()` and should be inherited by functions from the caller's namespace.  However, this doesn't seem to be the case.

**Comment by bcoca** [comment]
closed via #399
