### ISSUE TITLE
known_hosts module fails on RHEL5 (python 2.4)

### ISSUE THREAD

**Issue by samh** [ansible/ansible-modules-extras#407]
##### Issue Type:

Bug Report
##### Environment:

RHEL5
##### Summary:

When running `known_hosts` again RHEL5, it fails because the "delete" argument to `tempfile.NamedTemporaryFile` was added in Python 2.6: https://docs.python.org/2/library/tempfile.html

```
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1429314002.36-240382345137902/known_hosts", line 1835, in ?
    main()
  File "/tmp/ansible-tmp-1429314002.36-240382345137902/known_hosts", line 236, in main
    results = enforce_state(module,module.params)
  File "/tmp/ansible-tmp-1429314002.36-240382345137902/known_hosts", line 102, in enforce_state
    sanity_check(module,host,key,sshkeygen)
  File "/tmp/ansible-tmp-1429314002.36-240382345137902/known_hosts", line 165, in sanity_check
    outf=tempfile.NamedTemporaryFile(delete=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete'
```
##### Steps To Reproduce:

Run `known_hosts` module against a RHEL5 target.

**Comment by bcoca** [comment]
please test against the PR above to confirm it solves the issue

**Comment by samh** [comment]
Yes, thanks, the PR fixes the problem.
