### ISSUE TITLE
ec2_vpc_igw has incorrect connection parameters

### ISSUE THREAD

**Issue by zectdev** [ansible/ansible-modules-extras#906]
I just tested the ec2_vpc_igw module and received the error below.  Looks like the ec2 connection object does not support 'get_all_internet_gateways'   After changing the aws boto connection parameters on line 136 from boto.ec2 to boto.vpc, the module worked perfect.  Reference boto documentation here https://boto.readthedocs.org/en/latest/ref/vpc.html#module-boto.vpc 

Should I fork the module and create a pull request?

Error below:

[2015-09-01 10:56:03,563: WARNING/Worker-7] TASK: [aws_vpc | Create an AWS VPC IGW] ***************************************
[2015-09-01 10:56:03,694: WARNING/Worker-7] failed: [localhost] => {"failed": true, "parsed": false}
[2015-09-01 10:56:03,694: WARNING/Worker-7] Traceback (most recent call last):
  File ".ansible/tmp/ansible-tmp-1441119363.57-281147633793472/ec2_vpc_igw", line 1963, in <module>
    main()
  File ".ansible/tmp/ansible-tmp-1441119363.57-281147633793472/ec2_vpc_igw", line 147, in main
    result = ensure_igw_present(connection, vpc_id, check_mode=module.check_mode)
  File ".ansible/tmp/ansible-tmp-1441119363.57-281147633793472/ec2_vpc_igw", line 92, in ensure_igw_present
    igws = vpc_conn.get_all_internet_gateways(
AttributeError: 'EC2Connection' object has no attribute 'get_all_internet_gateways'

**Comment by ghost** [comment]
Just to confirm that I received exactly the same error running against the devel branch and updating the line dbhirko mentiond (`cloud/amazon/etc_vpc_igw:136`) fixed my issue too

**Comment by sgzijl** [comment]
Same issue here. Proposed fix works here.

**Comment by abadger** [comment]
dbhirko submitted #918 which was merged a few days ago.  So closing the bug report.  Thanks!
