### ISSUE TITLE
pkg5_publisher throws KeyError with unexpected output from `pkg publisher -Ftsv`

### ISSUE THREAD

**Issue by prakashsurya** [ansible/ansible-modules-extras#975]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```
##### Summary:

I have a system with the output of publishers listed like so:

```
$ pkg publisher
PUBLISHER                             TYPE     STATUS   URI
delphix.com                           origin   online   file:///data/ips_repo/
ms.omniti.com                         origin   online   file:///data/ips_repo/
omnios                                origin   online   file:///data/ips_repo/
on-nightly                            origin   online   file:///net/pharos/export/pkg/dlpx-os-gate/nightly/repo.redist/
openindiana.org             
```

When I try to use the `pkg5_publisher` with the system configured like this, I get the following Python exception:

```
$ sudo python /tmp/ansible/ansible-tmp-1442291882.82-184265772797279/pkg5_publisher
Traceback (most recent call last):
  File "/tmp/ansible/ansible-tmp-1442291882.82-184265772797279/pkg5_publisher", line 1902, in <module>
    main()
  File "/tmp/ansible/ansible-tmp-1442291882.82-184265772797279/pkg5_publisher", line 95, in main
    modify_publisher(module, module.params)
  File "/tmp/ansible/ansible-tmp-1442291882.82-184265772797279/pkg5_publisher", line 102, in modify_publisher
    existing = get_publishers(module)
  File "/tmp/ansible/ansible-tmp-1442291882.82-184265772797279/pkg5_publisher", line 184, in get_publishers
    publishers[name][values['type']].append(values['uri'])
KeyError: ''
```

Looking at the source, `pkg5_publisher` tries to parse each line from the output of `pkg publisher -Ftsv` and assumes there will be a value for each column. Obviously this is not a valid assumption to make, as my system is proof this isn't guaranteed to be true, so it'd be nice of the module was able to handle this situation gracefully.

If I manually remove this publisher from the system with:

```
$ sudo pkg unset-publisher openindiana.org
$ pkg publisher -Ftsv
PUBLISHER   STICKY  PREFERRED   ENABLED TYPE    STATUS  URI
delphix.com true    true    true    origin  online  file:///data/ips_repo/
ms.omniti.com   true    false   true    origin  online  file:///data/ips_repo/
omnios  true    false   true    origin  online  file:///data/ips_repo/
on-nightly  true    false   true    origin  online  file:///net/pharos/export/pkg/dlpx-os-gate/nightly/repo.redist/
```

then the `pkg5_publisher` module will work, but the whole point of using this module is to remove the need to manually configure the system.

To make matters worse, I can't simply use:

```
- name: Remove openindiana.org Publisher
  command: pkg unset-publisher openindiana.org
```

prior to using `pkg5_publisher` because that command will fail if the publisher doesn't exist (e.g. on the second invocation of the playbook or role, after the publisher was removed the first time).

**Comment by mavit** [comment]
@prakashsurya: Do you have time to check whether pull request #2047 fixes this issue for you?

**Comment by twolittlepistols** [comment]
Sure. On another mis-configured system, I tried the following:
```
$ pkg publisher
PUBLISHER                             TYPE     STATUS   URI
delphix.com                           origin   online   file:///net/pharos/export/src/dlpx-pkg-gate/
ms.omniti.com                         origin   online   file:///net/pharos/export/src/dlpx-pkg-gate/
ms.omniti.com                         origin   online   http://pkg.omniti.com/omniti-ms/
omnios                                origin   online   file:///net/pharos/export/src/dlpx-pkg-gate/
omnios                                origin   online   http://pkg.omniti.com/omnios/r151012/
install-nightly

$ sudo python .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher
Traceback (most recent call last):
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 1812, in <module>
    main()
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 96, in main
    unset_publisher(module, module.params['name'])
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 149, in unset_publisher
    if not publisher in get_publishers(module):
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 183, in get_publishers
    publishers[name][values['type']].append(values['uri'])
KeyError: ''

$ wget -q https://patch-diff.githubusercontent.com/raw/ansible/ansible-modules-extras/pull/2047.diff
$ patch -p1 .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher < 2047.diff
patching file .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher

delphix@galaxy:/export/home/delphix$ sudo python .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher
{"msg": "", "changed": true, "results": [""], "rc": 0}
```
Looks good to me! :+1:  Thanks, I really appreciate the time spent fixing this.

**Comment by prakashsurya** [comment]
Sure. On another mis-configured system, I tried the following:

```
$ pkg publisher
PUBLISHER                             TYPE     STATUS   URI
delphix.com                           origin   online   file:///net/pharos/export/src/dlpx-pkg-gate/
ms.omniti.com                         origin   online   file:///net/pharos/export/src/dlpx-pkg-gate/
ms.omniti.com                         origin   online   http://pkg.omniti.com/omniti-ms/
omnios                                origin   online   file:///net/pharos/export/src/dlpx-pkg-gate/
omnios                                origin   online   http://pkg.omniti.com/omnios/r151012/
install-nightly

$ sudo python .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher
Traceback (most recent call last):
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 1812, in <module>
    main()
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 96, in main
    unset_publisher(module, module.params['name'])
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 149, in unset_publisher
    if not publisher in get_publishers(module):
  File ".ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher", line 183, in get_publishers
    publishers[name][values['type']].append(values['uri'])
KeyError: ''

$ wget -q https://patch-diff.githubusercontent.com/raw/ansible/ansible-modules-extras/pull/2047.diff
$ patch -p1 .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher < 2047.diff
patching file .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher

delphix@galaxy:/export/home/delphix$ sudo python .ansible/tmp/ansible-tmp-1461440729.41-234544355526753/pkg5_publisher
{"msg": "", "changed": true, "results": [""], "rc": 0}
```

Looks good to me! :+1: Thanks, I really appreciate the time spent fixing this.
